name: lmt
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - cython
  - h5py
  - pyyaml
  - requests
  - mpmath
  - decorator
  - pint
  - matplotlib
  - pip:
    - h5py-wrapper
