name: lmt_temp
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - numpy
  - scipy
  - cython
  - h5py
  - pyyaml
  - requests
  - mpmath
  - decorator
  - pint
  - pytest
  - pytest-cov
  - pytest-mock 
  - matplotlib
  - pip
  - pip:
    - h5py-wrapper
